In [2]:
#Arrays are the most powerful and useful features in Julia. Let's start with some basics 

In [3]:
ele = ["car","bike","Cycle","Motorbike"]

4-element Vector{String}:
 "car"
 "bike"
 "Cycle"
 "Motorbike"

In [4]:
typeof(ele)

Vector{String} (alias for Array{String, 1})

In [5]:
num = [1, 2, 3, 4, 5, 6, 7, 8]

8-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8

In [6]:
typeof(num)

Vector{Int64} (alias for Array{Int64, 1})

In [27]:
push!(num, 100) # add element at last

10-element Vector{Int64}:
   1
   2
   3
   4
   5
   6
 100
 100
 100
 100

In [24]:
@show num

num = [1, 2, 3, 4, 5, 6, 100, 100, 100, 100]


10-element Vector{Int64}:
   1
   2
   3
   4
   5
   6
 100
 100
 100
 100

In [28]:
pop!(num) # remove from last

100

In [29]:
@show num

num = [1, 2, 3, 4, 5, 6, 100, 100, 100]


9-element Vector{Int64}:
   1
   2
   3
   4
   5
   6
 100
 100
 100

In [30]:
# 2-D Arrays

In [39]:
mat = [[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9, 1000]]

3-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5, 6]
 [7, 8, 9, 1000]

In [40]:
typeof(mat) # each element in Array is itself an Array 


Vector{Vector{Int64}} (alias for Array{Array{Int64, 1}, 1})

In [41]:
# Matrices

In [42]:
x = [1 2 3] # lack of commas and (the Dimension)
x

1×3 Matrix{Int64}:
 1  2  3

In [44]:
x' # turn this into a column matrix (transpose)

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 2
 3

In [51]:
# this work on if every list in list have same number of elements
mat = [
    [1 2 3 4]
    [5 6 7 8]
    [9 4 2 4]
    ]

3×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8
 9  4  2  4

In [52]:
mat'

4×3 adjoint(::Matrix{Int64}) with eltype Int64:
 1  5  9
 2  6  4
 3  7  2
 4  8  4

In [53]:
typeof(mat)

Matrix{Int64} (alias for Array{Int64, 2})

In [54]:
size(mat) # 3 rows and 4 columns

(3, 4)

In [56]:
size(x) # 1 row and 3 columns

(1, 3)

In [58]:
size(num) # Difference Important

(9,)

In [59]:
mat

3×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8
 9  4  2  4

In [65]:
mat2 = reshape(mat,4,3) 

4×3 Matrix{Int64}:
 1  6  2
 5  4  4
 9  3  8
 2  7  4

In [68]:
mat3 = reshape(mat,1,12) 

1×12 Matrix{Int64}:
 1  5  9  2  6  4  3  7  2  4  8  4

In [69]:
mat4 = reshape(mat,12,1) 

12×1 Matrix{Int64}:
 1
 5
 9
 2
 6
 4
 3
 7
 2
 4
 8
 4

In [70]:
mat5 = reshape(mat,3,4)

3×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8
 9  4  2  4

In [71]:
# Helper Function

In [75]:
rand(5,5)

5×5 Matrix{Float64}:
 0.101696  0.2691     0.42544    0.132017  0.293716
 0.689725  0.6523     0.0997285  0.149894  0.563845
 0.14839   0.090664   0.494213   0.934018  0.588112
 0.280161  0.739866   0.732165   0.499098  0.378565
 0.728578  0.0692716  0.377033   0.511336  0.523418

In [76]:
randn(3,3)

3×3 Matrix{Float64}:
  0.758602  -0.0253149  -0.195876
  1.25708   -0.587976    1.23954
 -1.43333    0.773187   -0.345254

In [77]:
mat6 = rand(5,5)

5×5 Matrix{Float64}:
 0.298413  0.98704   0.611334  0.564293  0.482775
 0.014252  0.165376  0.410201  0.71081   0.939948
 0.983723  0.107903  0.760706  0.88952   0.55698
 0.587506  0.903412  0.177653  0.471294  0.530244
 0.379498  0.682551  0.78672   0.306932  0.459542

In [78]:
mat7 = mat6

5×5 Matrix{Float64}:
 0.298413  0.98704   0.611334  0.564293  0.482775
 0.014252  0.165376  0.410201  0.71081   0.939948
 0.983723  0.107903  0.760706  0.88952   0.55698
 0.587506  0.903412  0.177653  0.471294  0.530244
 0.379498  0.682551  0.78672   0.306932  0.459542

In [79]:
mat7[4, 4] = 9999

9999

In [80]:
mat7

5×5 Matrix{Float64}:
 0.298413  0.98704   0.611334     0.564293  0.482775
 0.014252  0.165376  0.410201     0.71081   0.939948
 0.983723  0.107903  0.760706     0.88952   0.55698
 0.587506  0.903412  0.177653  9999.0       0.530244
 0.379498  0.682551  0.78672      0.306932  0.459542

In [87]:
mat7[5,5]

0.4595422912456393

In [88]:
#Copying Arrays

In [89]:
mat8 = copy(mat6)

5×5 Matrix{Float64}:
 0.298413  0.98704   0.611334     0.564293  0.482775
 0.014252  0.165376  0.410201     0.71081   0.939948
 0.983723  0.107903  0.760706     0.88952   0.55698
 0.587506  0.903412  0.177653  9999.0       0.530244
 0.379498  0.682551  0.78672      0.306932  0.459542

In [90]:
mat7[4,5] = 000000

0

In [91]:
mat7

5×5 Matrix{Float64}:
 0.298413  0.98704   0.611334     0.564293  0.482775
 0.014252  0.165376  0.410201     0.71081   0.939948
 0.983723  0.107903  0.760706     0.88952   0.55698
 0.587506  0.903412  0.177653  9999.0       0.0
 0.379498  0.682551  0.78672      0.306932  0.459542

In [92]:
# Comprehension

In [93]:
[i for i in 1:10]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [96]:
[(i, j) for i in 1:5, j in 6:10] # for carteian product or nested loop

5×5 Matrix{Tuple{Int64, Int64}}:
 (1, 6)  (1, 7)  (1, 8)  (1, 9)  (1, 10)
 (2, 6)  (2, 7)  (2, 8)  (2, 9)  (2, 10)
 (3, 6)  (3, 7)  (3, 8)  (3, 9)  (3, 10)
 (4, 6)  (4, 7)  (4, 8)  (4, 9)  (4, 10)
 (5, 6)  (5, 7)  (5, 8)  (5, 9)  (5, 10)

In [111]:
[(i^3, j) for i in 1:5, j in 6:10] # for carteian product/ nested loop have type Tuple

5×5 Matrix{Tuple{Int64, Int64}}:
 (1, 6)    (1, 7)    (1, 8)    (1, 9)    (1, 10)
 (8, 6)    (8, 7)    (8, 8)    (8, 9)    (8, 10)
 (27, 6)   (27, 7)   (27, 8)   (27, 9)   (27, 10)
 (64, 6)   (64, 7)   (64, 8)   (64, 9)   (64, 10)
 (125, 6)  (125, 7)  (125, 8)  (125, 9)  (125, 10)

In [112]:
# Matrix Operation

In [117]:
A = rand(5:10,3,3) # 3x4 matrix values btw 5-10

3×3 Matrix{Int64}:
  6  10   8
 10   6  10
  9  10   9

In [125]:
A = rand(5:10.0,3,3) # 3x4 matrix values btw 5-10 having float data type

3×3 Matrix{Float64}:
 9.0  8.0  9.0
 7.0  5.0  5.0
 9.0  7.0  8.0

In [139]:
y = fill(2, (3,3)) # instead random values you can give specific value

3×3 Matrix{Int64}:
 2  2  2
 2  2  2
 2  2  2

In [166]:
z = A * y # add element of A row wise then multiple

3×3 Matrix{Float64}:
 52.0  52.0  52.0
 34.0  34.0  34.0
 48.0  48.0  48.0

In [167]:
z'

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 52.0  34.0  48.0
 52.0  34.0  48.0
 52.0  34.0  48.0

In [168]:
z * z

3×3 Matrix{Float64}:
 6968.0  6968.0  6968.0
 4556.0  4556.0  4556.0
 6432.0  6432.0  6432.0

In [169]:
z

3×3 Matrix{Float64}:
 52.0  52.0  52.0
 34.0  34.0  34.0
 48.0  48.0  48.0

In [170]:
z + z 

3×3 Matrix{Float64}:
 104.0  104.0  104.0
  68.0   68.0   68.0
  96.0   96.0   96.0

In [171]:
z - z

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [172]:
tr(z)

134.0

In [173]:
using LinearAlgebra # to solve tr() trace error

In [176]:
det(z)

0.0

In [183]:
b = z'z

3×3 Matrix{Float64}:
 6164.0  6164.0  6164.0
 6164.0  6164.0  6164.0
 6164.0  6164.0  6164.0

In [190]:
b = rand(2:4,3,3)

3×3 Matrix{Int64}:
 3  3  2
 4  3  2
 3  3  4

In [192]:
inv(b)

3×3 Matrix{Float64}:
 -1.0       1.0  -0.0
  1.66667  -1.0  -0.333333
 -0.5       0.0   0.5

In [193]:
rand(1,2,3) # 3 array outer than 1 row and two column 

1×2×3 Array{Float64, 3}:
[:, :, 1] =
 0.727683  0.438732

[:, :, 2] =
 0.49159  0.636954

[:, :, 3] =
 0.0149855  0.493784

In [196]:
rand(1,2,3,4) # you can create any number of dimention array

1×2×3×4 Array{Float64, 4}:
[:, :, 1, 1] =
 0.00383408  0.105277

[:, :, 2, 1] =
 0.980263  0.719664

[:, :, 3, 1] =
 0.44779  0.402157

[:, :, 1, 2] =
 0.831996  0.168807

[:, :, 2, 2] =
 0.84296  0.748647

[:, :, 3, 2] =
 0.0500278  0.786605

[:, :, 1, 3] =
 0.474372  0.0647256

[:, :, 2, 3] =
 0.960769  0.551638

[:, :, 3, 3] =
 0.859985  0.110831

[:, :, 1, 4] =
 0.918031  0.865503

[:, :, 2, 4] =
 0.0692495  0.350891

[:, :, 3, 4] =
 0.317428  0.262524